spring:
  profiles:
    active: non-prod
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: aviyan.auto.email@gmail.com
    password: opzlylbjomukfugr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      protocol: smtp
      test-connection: false
aviyan:
  app:
    jwtSecret: aviyanSecret
    jwtExpirationMs: 86400000

---
spring:
  config:
    activate:
      on-profile: non-prod

aviyan:
  db:
    driver: org.h2.Driver
    url: jdbc:h2:file:./aviyan_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: SA
    password:

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port : 80

aviyan:
  db:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aviyan-db.cjxypfnbtoek.ap-south-1.rds.amazonaws.com:3306/aviyandb
    username: aviyandb
    password: aviyandb